# Models for apartment prices, snippets for Python

In [1]:
import dalex as dx
apartments = dx.datasets.load_apartments()
X = apartments.drop(columns='m2_price')
y = apartments['m2_price']

In [2]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

preprocess = make_column_transformer(
    (StandardScaler(), ['construction_year', 'surface', 'floor', 'no_rooms']),
    (OneHotEncoder(), ['district']))

# Linear regression model

In [3]:
from sklearn.linear_model import LinearRegression

apartments_lm = make_pipeline(
    preprocess,
    LinearRegression())
apartments_lm.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['construction_year',
                                                   'surface', 'floor',
                                                   'no_rooms']),
                                                 ('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['district'])])),
                ('linearregression', LinearRegression())])

# Random forest model

In [4]:
from sklearn.ensemble import RandomForestRegressor

apartments_rf = make_pipeline(
    preprocess,
    RandomForestRegressor(max_depth = 3, n_estimators = 500))
apartments_rf.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['construction_year',
                                                   'surface', 'floor',
                                                   'no_rooms']),
                                                 ('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['district'])])),
                ('randomforestregressor',
                 RandomForestRegressor(max_depth=3, n_estimators=500))])

# Support vector machine model

In [5]:
from sklearn.svm import SVR

apartments_svm = make_pipeline(
    preprocess,
    SVR())
apartments_svm.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['construction_year',
                                                   'surface', 'floor',
                                                   'no_rooms']),
                                                 ('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['district'])])),
                ('svr', SVR())])

# Models’ predictions

In [6]:
apartments_test = dx.datasets.load_apartments_test()
apartments_test = apartments_test.drop(columns='m2_price')

apartments_lm.predict(apartments_test)
# array([4820.00943156, 3292.67756996, 2717.90972101, ..., 4836.44370353,
#        3191.69063189, 5157.93680175])

array([4820.00943156, 3292.67756996, 2717.90972101, ..., 4836.44370353,
       3191.69063189, 5157.93680175])

In [7]:
apartments_rf.predict(apartments_test)
# array([4708, 3819, 2273, ..., 4708, 4336, 4916])

array([4784.04214223, 2870.71321105, 2809.46115441, ..., 4807.72255387,
       3147.1009052 , 4848.45980961])

In [8]:
apartments_svm.predict(apartments_test)
# array([3344.48570564, 3323.01215313, 3321.97053977, ..., 3353.19750146,
#        3383.51743883, 3376.31070911])

array([3344.48570564, 3323.01215313, 3321.97053977, ..., 3353.19750146,
       3383.51743883, 3376.31070911])

# Models’ explainers

In [9]:
apartments_lm_exp = dx.Explainer(apartments_lm, X, y, 
                      label = "Apartments LM Pipeline")
apartments_rf_exp = dx.Explainer(apartments_rf, X, y, 
                      label = "Apartments RF Pipeline")
apartments_svm_exp = dx.Explainer(apartments_svm, X, y, 
                      label = "Apartments SVM Pipeline")

Preparation of a new explainer is initiated

  -> data              : 1000 rows 5 cols
  -> target variable   : Parameter 'y' was a pandas.Series. Converted to a numpy.ndarray.
  -> target variable   : 1000 values
  -> model_class       : sklearn.linear_model._base.LinearRegression (default)
  -> label             : Apartments LM Pipeline
  -> predict function  : <function yhat_default at 0x7fd83234e940> will be used (default)
  -> predict function  : Accepts only pandas.DataFrame, numpy.ndarray causes problems.
  -> predicted values  : min = 1.78e+03, mean = 3.49e+03, max = 6.18e+03
  -> model type        : regression will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -2.47e+02, mean = 8.69e-14, max = 4.69e+02
  -> model_info        : package sklearn

A new explainer has been created!
Preparation of a new explainer is initiated

  -> data              : 1000 rows 5 cols
  -> target variable   : Parameter 'y' was a pan